### ISSUE TITLE
从零开始React项目架构(一)：环境搭建

### ISSUE THREAD

**Issue by ZeroCodeLin** [l-Lemon/blog#1]
### 前言
---
零零散散也做过不少项目了，有基于jquery、bootstrap的，有基于jquery、easyui的，有基于react的。

项目多了总会有一些自己感悟和经验，所以分享出来，肯定有不对和不合适的地方，欢迎批评指正。

好了，废话不多说了，让我们从零开始，一步一步的折腾吧。

### 开发
---
### 一、初始化项目
1. 创建项目文件，就叫 `react-architecture` 吧。
2. 初始化git  `git init`
3. 初始化npm `npm init`
4. 当然不能一口气只讲配置，so 我们简单的创建一些文件和目录，跑起来看一看效果。目录结构如下：
``` shell
├── src                     
│   ├── index.html                
│   └── index.js                              
├── .gitignore
├── package-lock.json
├── package.json
└── webpack.config.js
```
我们先来配置下webpack，暂时先不管其他。

### 二、webpack.config.js 的配置
1. 安装一些依赖:  为了webpack运行，需要安装
```shell
    npm install -D webpack@3 webpack-dev-server@2 html-webpack-plugin
```
react，需要安装
```shell
    npm install -S react react-dom react-router-dom
```
处理less，需要安装
```shell
    npm install -D css-loader style-loader less less-loader
```
处理图片和字体文件，需要安装
```shell
    npm install -D url-loader file-loader
```
为了支持高级语法-babel，需要安装
```shell
    npm install -S babel-polyfill // 实际生产环境也会用到
    npm install -D babel-core babel-loader babel-preset-env babel-preset-react babel-preset-stage-2 
```

2. webpack.config.js 配置
```javascript
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const webpack = require('webpack')

module.exports = {
    entry:{
        main:['babel-polyfill','./src/index.js'],
    },
    output:{
        path:path.resolve(__dirname,'dist'),
        filename:'bundle.js'
    },
    module:{
        rules:[
            {  
                test: /\.(woff|eot|ttf|svg|png|jpg)$/,  
                use: [  
                    {  
                        loader: 'url-loader',  
                        options: {  
                            limit: '1024'  
                        }  
                    },  
                ]  
            },
            {  
                test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
                use: [  
                    {  
                        loader: 'url-loader',  
                        options: {  
                            limit: '1024'  
                        }  
                    },  
                ]  
            },
            {
                test: /\.(css|less)$/,
                use: [
                    'style-loader',
                    { 
                        loader: 'css-loader',
                        options: { importLoaders: 1 } 
                    },
                    'less-loader'
                ]
            },
            {
                test:/\.(js|jsx)$/,
                use:"babel-loader",
                exclude:/node_modules/
            }
        ]
    },
    plugins:[
        new HtmlWebpackPlugin({template:'./src/index.html'}),
    ],
    devServer:{
        contentBase: path.join(__dirname, "dist"),
        compress: true,
        port: 9000,
        proxy: {
            "/api": {
              target: "http://127.0.0.1:3000/",
              pathRewrite: {"^/api" : ""}
            }
          }
    }
}
```
3. babel的配置  
创建`.babelrc`文件
```babelrc
{
    "presets": [
        ["env",{
            "targets": {
                "browsers": ["IE >= 9"]
            },
            "useBuiltIns": true
        }],
        "react",
        "stage-2"
    ]
}
```
4. index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>react-architecture</title>
</head>
<body>
    <div id="root"></div>
</body>
</html>
```
5. index.js  
万变不离Hello World~
```javascript
import React from 'react'
import ReactDOM from 'react-dom'

ReactDOM.render(
    <h1>Hello World!</h1>,
    document.getElementById('root')
)
```
6. 在package.json的 scripts 添加启动命令 
```json
    "start": "webpack-dev-server --open"
```

7. 命令行 运行 `npm start` 就可以看效果了

### 总结
---
本章主要做了3件事：
1. 创建简单的项目文件
2. 安装所需要依赖
3. webpack、babel 开发环境的配置， Hello World 基本代码的编写

下篇文章将介绍 配置eslint 目录架构

**Comment by william-xue** [comment]
npm i -D babel-plugin-transfordecorators-legacy
npm i -D html-webpack-plugin
npm i webpack-cli -D
加上就可以了

**Comment by ZeroCodeLin** [comment]
@william-xue   webpack-cli 是webpack4.o，我用的是webpack3.+，所以不需要安装

**Comment by jeffywin** [comment]
Cannot find module 'foreach' 一直报这个错什么原因

**Comment by ZeroCodeLin** [comment]
@jeffywin 是安步骤下来报这个错吗？

**Comment by jeffywin** [comment]
是的，按步骤，后面都直接复制了
Error: Cannot find module 'foreach'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\17030361\Desktop\react-demo\node_modules\.1.1.2@define-properties\index.js:4:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-demo@1.0.0 start: `webpack-dev-server --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-demo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output abo

**Comment by jeffywin** [comment]
Error: Cannot find module 'foreach'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Desktop\react-demo\node_modules\.1.1.2@define-properties\index.js:4:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-demo@1.0.0 start: `webpack-dev-server --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-demo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output abo

**Comment by ZeroCodeLin** [comment]
@jeffywin  你看下webpack包是什么版本，我是使用的3.+版本，webpack-dev-server是2.+版本

**Comment by jeffywin** [comment]
webpack 4+运行不起来，尴尬了

**Comment by ZeroCodeLin** [comment]
@jeffywin  文章已更正。webpack 4+ 你可以`npm install -D webpack-cli  html-webpack-plugin babel-plugin-transfordecorators-legacy`  这样可以。或者安我修改后文章的来
